---
# tasks file for adminer
- name: create (download) directory
  file:
    path: /var/lib/ansible/adminer/downloads
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [configuration, adminer, adminer-download ]

- name: download (latest)
  get_url:
    url: http://www.adminer.org/latest.php
    dest: /var/lib/ansible/adminer/downloads/latest.php
    force: true
    owner: root
    group: root
    mode: 0644
  tags: [configuration, adminer, adminer-download]

- name: install
  file:
    src: /var/lib/ansible/adminer/downloads/latest.php
    dest: "{{ item }}/adminer.php"
    state: link
  with_items: adminer_install_dirs
  when: adminer_install_dirs is defined
  tags: [configuration, adminer, adminer-download ]
