# tasks file
---
- name: create (download) directory
  ansible.builtin.file:
    path: "{{ adminer_download_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - configuration
    - adminer
    - adminer-download

- name: download (latest)
  ansible.builtin.get_url:
    url: "{{ adminer_download_url }}"
    dest: "{{ adminer_download_path }}/latest.php"
    owner: root
    group: root
    mode: '0644'
    force: true
    timeout: 60
  tags:
    - configuration
    - adminer
    - adminer-download

- name: install
  ansible.builtin.file:
    src: "{{ adminer_download_path }}/latest.php"
    dest: "{{ item }}/adminer.php"
    state: link
    force: true
  with_items: "{{ adminer_install_dirs }}"
  tags:
    - configuration
    - adminer
    - adminer-install

- name: dark mode
  tags:
    - configuration
    - adminer
    - adminer-dark-mode
  block:
    - name: dark mode | disallow
      ansible.builtin.file:
        src: /dev/null
        dest: "{{ item }}/{{ adminer_css_file }}"
        state: link
        force: true
      when: adminer_no_darkmode | bool
      with_items: "{{ adminer_install_dirs }}"

    - name: dark mode | allow
      ansible.builtin.file:
        path: "{{ item }}/{{ adminer_css_file }}"
        state: absent
      when: not adminer_no_darkmode | bool
      with_items: "{{ adminer_install_dirs }}"
