# tasks file for adminer
---
- name: create (download) directory
  file:
    path: "{{ adminer_download_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - adminer
    - adminer-download

- name: download (latest)
  get_url:
    url: "{{ adminer_download_url }}"
    dest: "{{ adminer_download_path }}/latest.php"
    owner: root
    group: root
    mode: 0644
    force: true
  tags:
    - configuration
    - adminer
    - adminer-download

- name: install
  file:
    src: "{{ adminer_download_path }}/latest.php"
    dest: "{{ item }}/adminer.php"
    state: link
    force: true
  with_items: "{{ adminer_install_dirs }}"
  tags:
    - configuration
    - adminer
    - adminer-install
